name: Update GitHub Stats

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: github-stats
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&include_all_commits=true&theme=tokyonight&hide_border=true
          path: profile/stats.svg
          token: ${{ secrets.GH_STATS_TOKEN }}

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=8&hide=CMake,PLpgSQL,SCSS,Swift,C,Hack,Mako,Kotlin,Objective-C&theme=tokyonight&hide_border=true
          path: profile/top-langs.svg
          token: ${{ secrets.GH_STATS_TOKEN }}

      - name: Commit generated cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/*.svg

          if git diff --cached --quiet; then
            echo "No stats changes."
            exit 0
          fi

          git commit -m "chore: update GitHub stats"

          git pull --rebase origin master

          git push origin HEAD:master
